name: 'Mafia'
baseurl: /mafia
markdown: kramdown
highlighter: pygments
exclude: ['Rakefile', 'README.md', 'config.rb', '*.bat', '*.bak', 'scripts']
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
paginate: 10
paginate_path: /blog/page:num

sass:
  sass_dir: _sass
  style: :compressed
